-- 銘柄セクタ
CREATE TABLE sector_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 銘柄テーブル
CREATE TABLE IF NOT EXISTS security_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    code INT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    country_code INT NOT NULL,
    sector_id INT NOT NULL, -- セクターID
    FOREIGN KEY(sector_id) REFERENCES sector_data(id)
);

-- 証券会社
CREATE TABLE broker_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 所有者
CREATE TABLE owner_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 取引（履歴）テーブル
CREATE TABLE transaction_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    security_id INT NOT NULL, -- 銘柄ID
    broker_id INT NOT NULL, -- 証券会社ID
    purchase_price INT NOT NULL, -- 買い付け金額
    sale_price INT, -- 売却金額
    number_of_stocks INT NOT NULL,
    purchase_date DATE NOT NULL, -- 買い付け日
    sale_date DATE, -- 売却日
    buy_fee INT NOT NULL, -- 買い付け手数料
    sell_fee INT, --売却手数料
    current_price INT NOT NULL, -- 現在の価格
    owner_id INT NOT NULL, -- 所有者ID
    FOREIGN KEY(owner_id) REFERENCES owner_data(id),
    FOREIGN KEY(security_id) REFERENCES security_data(id),
    FOREIGN KEY(broker_id) REFERENCES broker_data(id)
);
