services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SQL_INIT_MODE=never

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/vscode/.htpasswd:/etc/nginx/conf.d/.htpasswd
    depends_on:
      - app

volumes:
  db:
    driver: local
