services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
volumes:
  db:
    driver: local
