version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  db-data:
    driver: local
