spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/stock_db
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # スキーマファイルを優先
  sql:
    init:
      mode: always
      enabled: true
      schema-locations: classpath:schema-mysql.sql # 効いていないschema.sqlが参照されてしまう
      data-locations: classpath:data.sql
