-- 所有者
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 証券会社
CREATE TABLE brokers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 銘柄セクタ
CREATE TABLE sectors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL
);

-- 銘柄テーブル
CREATE TABLE IF NOT EXISTS stocks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    code INT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(16) NOT NULL,
    sector_id INT NOT NULL, -- セクターID
    FOREIGN KEY(sector_id) REFERENCES sectors(id)
);

-- 取引（履歴）テーブル
CREATE TABLE transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    owner_id INT NOT NULL, -- 所有者ID
    stock_id INT NOT NULL, -- 銘柄ID
    broker_id INT NOT NULL, -- 証券会社ID
    price_per_share INT NOT NULL, -- 1株あたりの取引金額
    transaction_type VARCHAR(8), -- 取引種別(BUYまたはSELL)
    quantity INT NOT NULL, -- 取引株数
    fee INT NOT NULL, -- 取引手数料
    transaction_at DATE, -- 取引日
    FOREIGN KEY(owner_id) REFERENCES owners(id),
    FOREIGN KEY(stock_id) REFERENCES stocks(id),
    FOREIGN KEY(broker_id) REFERENCES brokers(id)
);

-- 配当＆優待金（履歴）テーブル
CREATE TABLE dividend_and_preferentials (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    stock_id INT NOT NULL, -- 銘柄ID
    dividenv_price INT NOT NULL, -- 1株あたりの取引金額
    fee INT NOT NULL, -- 手数料
    transaction_at DATE, -- 取引日
    FOREIGN KEY(stock_id) REFERENCES stocks(id)
);

-- 所有株テーブル
CREATE TABLE holdings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    owner_id INT NOT NULL, -- 所有者ID
    stock_id INT NOT NULL, -- 銘柄ID
    quantity INT NOT NULL, -- 取引株数
    average_price INT NOT NULL, -- 購入にかかった平均取得単価
    total_dividend INT NOT NULL, -- Total配当金
    total_preferential INT NOT NULL, -- Total優待金
    updated_at DATE, -- 最終更新日時
    FOREIGN KEY(owner_id) REFERENCES owners(id),
    FOREIGN KEY(stock_id) REFERENCES stocks(id)
)
