package com.example.stock.model

import jakarta.persistence.Entity
import jakarta.persistence.Table
import jakarta.persistence.GenerationType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Column

@Entity
@Table(name = "stocks")
data class Stocks(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    @Column(name = "code", nullable = false, unique = true)
    val code: String,

    @Column(name = "name", nullable = false, unique = true)
    val name: String,

    @Column(name = "country", nullable = false)
    val country: String,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sector_id", nullable = false)
    val sector_id: Sectors
)
/* 
-- 銘柄テーブル
CREATE TABLE IF NOT EXISTS stocks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    code INT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(16) NOT NULL,
    sector_id INT NOT NULL, -- セクターID
    FOREIGN KEY(sector_id) REFERENCES sectors(id)
);
 */